---
- hosts: localhost
  connection: local
  tasks:

    # Install NVIDIA Driver

    - name: Add NVIDIA apt preferences
      get_url:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
        dest: /etc/apt/preferences.d/cuda-repository-pin-600

    - name: Add CUDA apt key
      apt_key:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
        state: present

    - name: Add CUDA Repository
      apt_repository:
        repo: deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /
        state: present

    - name: Install CUDA driver
      apt:
        name: cuda
        state: latest
        update_cache: yes
    
    # Install Docker

    - name: Install Docker prerequisites
      apt:
        name:
        - 'apt-transport-https'
        - 'ca-certificates'
        - 'curl'
        - 'gnupg-agent'
        - 'software-properties-common'
        state: present
        update_cache: yes

    - name: Add docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker CE
      apt:
        name:
        - 'docker-ce'
        - 'docker-ce-cli'
        - 'containerd.io'
        state: latest
        update_cache: yes
    
    - name: Add docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.4/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
        dest: /usr/local/bin/docker-compose
        owner: root
        group: root
        mode: 0755
    
    # Install NVIDIA Container Toolkit

    - name: Add NVIDIA apt key
      apt_key:
        url: https://nvidia.github.io/nvidia-docker/gpgkey
        state: present

    - name: Add NVIDIA apt sources
      get_url:
        url: https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list
        dest: /etc/apt/sources.list.d/nvidia-docker.list

    - name: Install NVIDIA Container Toolkit
      apt:
        name: nvidia-container-toolkit
        state: latest
        update_cache: yes
      notify:
        - restart docker

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
