---
- hosts: localhost
  connection: local
  vars:
    user: root
    k3d_tag: v3.0.0-rc.6
  strategy: free
  gather_facts: no
  remote_user: "{{ user }}"
  become: yes
  tasks:
    - name: install curl
      apt:
        name: curl
        state: present
    - name: download k3d installation script
      get_url:
        url: https://raw.githubusercontent.com/rancher/k3d/main/install.sh
        dest: /tmp/k3d.sh
        mode: "u=rwx,g=rx,o=rx"
    - name: install k3d
      shell: /tmp/k3d.sh
      environment:
        TAG: "{{ k3d_tag }}"
    - name: check k3d version
      shell: k3d version
      register: k3d
    - debug:
        msg: "{{k3d.stdout}}"
